### ISSUE TITLE
Map Recommendation using score instead of index

### ISSUE THREAD

**Issue by sythel** [dams-mcda/Dams-MCDA#137] opened 2019-09-19 17:03 UTC
fix incoming

**Comment by sythel** [comment] 2019-09-19 17:12
IdxRank top result shows:
(Score of 700) 0,0,1,0,1,0,0,0 (Map Index 89)
map 89 png shows:
3,2,0,0,0,0,0,1

**Comment by sythel** [comment] 2019-09-19 17:13
this may be due to the weird test preferences I have been using

**Comment by sythel** [comment] 2019-09-19 17:37
@elbfox is the ordering of Dams in Decisions.RData the same as the order of the dams in the application?

IdxRank top result shows:
 0,0,1,0,1,0,0,0

map 88 shows:
0,0,1,0,0,0,0,1


also it seems map 62 doesn't match Decisions matrix but if the dams were out of order it could explain this

**Comment by elbfox** [comment] 2019-09-19 18:43
Closing #136 then. Notes from there:

Multi-dam result maps do not generate as one might expect. For instance, with extreme preferences, like 100% toward any given criterion, the result is strange (like improve hydropower at most, remove some, and keep one for fish preferences).

TESTING:
(1) @sythel you mentioned at some point that you needed to test the mapped output...is this like No. 3 (see below), or did you have something else in mind?
(2) @elbfox to check that local version selection matches live version selection
(3) @elbfox and @sythel to test a few different preferences to see if the dam decision numbers (e.g. 0=keep and maintain) match what appears on the map (i.e., is the right map being selected)

**Comment by elbfox** [comment] 2019-09-20 15:41
@sythel I emailed @samGroy about the Decisions.RData, because I can't tell the order of the dams based on the information I have here. I think that the dams would have to be ordered really differently in the Decisions.RData to come up with the results you shared. 

Regardless, I will need to reorder the dams from downstream to upstream, so this may mean ordering them in Decisions.RData as well. Right now, I know this change entails: switching the organization in ui.R, renaming variables explicit reference to the dam _name_ as opposed to the dam _number_ , reordering damsdata.csv.

**Comment by elbfox** [comment] 2019-09-20 20:31
Ok, I think I've cracked it. At some point, I reordered the decision alternatives, as well as the dams. So, I am making those changes now to be consistent with Sam's f_nrge dataset. We will still need the rules for normalizing  and specific decision alternative priorities, because those problems are specific to the criteria/dam pairing (and _also_ occur in the individual dams dataset, where the ordering of the decision alternatives/dams doesn't matter as long as it's internally consistent). 

**My task for the foreseeable future:** re-order all dams and decision alternatives in WSM.R, ui.R, server.R to match what we gave Sam. This includes labels and the actual organization of the app, as well as the DamsData.csv. None of this should impact your rule-making, but it will give us a major headache when it comes to merging our branches.

**Comment by sythel** [comment] 2019-09-20 20:35
(max alt selecting rules lines: 1114-1196)https://github.com/dams-mcda/Dams-MCDA/blob/cbeda1d33364587fb02ee907fb6881ef79834920/src/dams_mcda/server.R#L1114

**Comment by elbfox** [comment] 2019-09-20 21:42
This looks like a good fix, and will work after I get done switching the dams and decision alternatives around.

**Comment by elbfox** [comment] 2019-09-21 13:50
From Sam: "[maps] ordered by latitude I believe, so there could be some weird quirks. Also note that the map number digits are one less than the ranks (example, scenario 1 is map 0)."

**Comment by elbfox** [comment] 2019-09-21 16:37
Working on ordering dams by latitude like this, now:

West Enfield Dam
Medway Dam
East Millinocket Dam
Dolby Dam
North Twin Dam
Millinocket Development
Millinocket Lake Dam
Ripogenus Dam

**Comment by elbfox** [comment] 2019-09-23 13:01
Dams in f_nrge currently ordered by DamID (DID): 

Dolby dam (DID 3395)
Millinocket Lake Dam (DID 3396)
Millinocket/Quakish Lake (DID 3398)
North Twin (DID 3399)
Ripogenus (DID3409)
East Millinocket (DID 3940)
Medway (DID 3942)
West Enfield (DID 3969)

_These need to be re-ordered by latitude as above._ @sythel is this something you can do? I'm working on launching a survey today and can't get to it until tomorrow, earliest. This will probably solve our map issue, along with the knowledge that map number digits are one less than the rank (e.g., scenario is 1, map is 0).

**Comment by sythel** [comment] 2019-09-23 21:31
Millinocket Dev == Millinocket Quakish?

**Comment by elbfox** [comment] 2019-09-23 21:53
Yes, sorry for any confusion that may have caused. Many of the dams have more than one name, for some reason, so it's been a real trial to get those naming differences reconciled.

**Comment by sythel** [comment] 2019-09-23 22:16
test fix in commit 6a6651d09d63becf27214f53d45e8332b62e3c38

**Comment by elbfox** [comment] 2019-09-24 13:22
> test fix in commit [6a6651d](https://github.com/dams-mcda/Dams-MCDA/commit/6a6651d09d63becf27214f53d45e8332b62e3c38)

Is this commit in the live version?

**Comment by sythel** [comment] 2019-09-24 14:51
its live as of now

**Comment by elbfox** [comment] 2019-09-24 17:04
Ok, there is still a disconnect between multi-dam output and mapped output after this test fix. Here are some of the files I've been using to test. 
[EqualPrefs_forLiveSite.xlsx](https://github.com/dams-mcda/Dams-MCDA/files/3648420/EqualPrefs_forLiveSite.xlsx)
[FishPrefs_forLiveSite.xlsx](https://github.com/dams-mcda/Dams-MCDA/files/3648423/FishPrefs_forLiveSite.xlsx)
[HydroPrefs_forLiveSite.xlsx](https://github.com/dams-mcda/Dams-MCDA/files/3648424/HydroPrefs_forLiveSite.xlsx)

**Comment by elbfox** [comment] 2019-09-24 17:08
Sharon tried using these and gets the error message 
"File is invalid:. Please verify you are uploading the correct file or try a different file."

But they all work for me.

**Comment by sythel** [comment] 2019-09-24 17:20
is she uploading them as .csv files

**Comment by elbfox** [comment] 2019-09-24 17:36
Yes

**Comment by elbfox** [comment] 2019-09-24 17:36
She has a Mac, if that makes a difference

**Comment by sythel** [comment] 2019-09-24 17:55
shouldn't make a difference on mac, if you can source the exact file she is using I may be able to figure it out

**Comment by elbfox** [comment] 2019-09-24 17:57
I'll have to email them to you because I can't add them here as CSVs. They're the same files I added above but with the .csv file extension. Emailing now.

**Comment by sythel** [comment] 2019-09-24 18:04
works ok for me
try logging out, clearing web browser cache, logging back in
then see if it persists

**Comment by elbfox** [comment] 2019-09-25 15:30
This one doesn't work, either. Clear mismatch between maps and multi-dam results in IndividualDamOutput branch. 

![image](https://user-images.githubusercontent.com/19410104/65615748-d7772700-df87-11e9-9910-22f2e22fcd1b.png)
![image](https://user-images.githubusercontent.com/19410104/65615796-ec53ba80-df87-11e9-93ad-6c4ae3bb5c15.png)

**Comment by elbfox** [comment] 2019-09-25 19:38
> Also note that the map number digits are one less than the ranks (example, scenario 1 is map 0)." Did this get addressed in the test fix in commit 6a6651d ?

**Comment by sythel** [comment] 2019-09-25 19:42
not in that commit, but is in master now

change that fixed this was 
old
```
idxScen <- c(1:995)
```
new
```
idxScen <- c(0:994)
```

**Comment by elbfox** [comment] 2019-09-25 19:44
ok thank you I will continue to test.

**Comment by sythel** [comment] 2019-09-25 21:04
hard to debug what's wrong...
something with Normalization &/or Decisions is my best guess.

what would be the best way to verify that we have the dam ordering* right?
(*ordering for Decisions and f_nrge)

sadly I won't be around tomorrow; but I will be on friday.
if its still a problem it may be worth checking out the code that generated these files

**Comment by elbfox** [comment] 2019-09-25 21:38
> not in that commit, but is in master now
> 
> change that fixed this was
> old
> 
> ```
> idxScen <- c(1:995)
> ```
> 
> new
> 
> ```
> idxScen <- c(0:994)
> ```

Is the master version live right now? In Decisions and f_nrge, Sam confirmed that the original files are ordered like this: 
Dolby dam (DID 3395)
Millinocket Lake Dam (DID 3396)
Millinocket/Quakish Lake (DID 3398)
North Twin (DID 3399)
Ripogenus (DID3409)
East Millinocket (DID 3940)
Medway (DID 3942)
West Enfield (DID 3969)

So the changes you made should have ordered them properly. The only other thing I can think of right now is that the social/cultural criteria values are driving the differences....Sam had old data in f_nrge/NormalizedMatrix (and so Decisions is impacted by that). The social/cultural criteria values we are using in DamsData.csv (e.g. Indigenous cultural traditions and lifeways, community identity, industrial historical importance, aesthetics, public health, and socio-environmental justice) are actually different from what he has in the f_nrge.RData file. I didn't think the differences were significant enough to make the results diverge this much, but I guess it's possible. We won't be able to fix this until Monday, when Sam re-runs the MOGA, unless we use the RMatlab package.

**Comment by elbfox** [comment] 2019-09-25 22:21
> [max alt selecting rules lines: 1114-1196](https://github.com/dams-mcda/Dams-MCDA/blob/cbeda1d33364587fb02ee907fb6881ef79834920/src/dams_mcda/server.R#L1114)

Another idea just came to mind. This code ^ identifies priority alternatives for dams with the conditions we discussed in #133, but it looks like it's doing it after the MCDA calculation has happened? Is it layering on top of what I wrote and kept in as a placeholder? 
````	NormalizedMatrix[3,6,] <- 1 #This replaces the properties NaN <-- 0 with 0 <-- 1 for East Millinocket
	NormalizedMatrix[2,1,] <- 1 #This replaces fish habitat NaN at Medway
	NormalizedMatrix[1:3,3, ] <- 1#This replaces the reservoir storage NaN at West Enfield, Medway, East Mill
	NormalizedMatrix[7,2,] <- 1 #This replaces the river rec NaN at Millinocket Lake
````
If it the max alt selection "rules" are happening after the MCDA calculation, I can just take out the normalization code (above) I included in the NormalizationChanges branch, because it seems like the decision alternatives are being prioritized twice, maybe.

**Comment by sythel** [comment] 2019-09-27 15:41
> it looks like it's doing it after the MCDA calculation has happened? Is it layering on top of what I wrote and kept in as a placeholder?

correct

**Comment by elbfox** [comment] 2019-09-27 15:57
Ok, removed.

**Comment by elbfox** [comment] 2019-09-29 01:04
I have tested this over and over locally, and it looks like the idxScen is outputting the right multi-dam map based on the decision alternative codes: 

0 = remove dam
1 = keep as is
2 = improve hydropower
3 = improve fish passage
4 = improve both

Like we thought, it means that the multi-dam dataset is definitely the issue right now. I'm going to close this issue and have just opened #151 with a refined definition specific to the multi-dam results not matching the individual dam results.

**Closed by elbfox** 2019-09-29 01:04 UTC
Labels: bug
